CREATE DATABASE DBMedellin_Turismo

USE DBMedellin_Turismo

CREATE TABLE USUARIO (
    ID INT IDENTITY PRIMARY KEY,
    Nombre NVARCHAR(100),
    Correo NVARCHAR(100) UNIQUE,
    Contraseña NVARCHAR(255),
	Rol NVARCHAR (100)
);

CREATE TABLE LUGAR (
    ID INT IDENTITY PRIMARY KEY,
    Nombre VARCHAR(150),
    Descripción VARCHAR(255),
    Categoría VARCHAR(100),
    Ubicación NVARCHAR(255),
    Imagen NVARCHAR(255),
    Horarios NVARCHAR(255),
    Contacto NVARCHAR(100)
);

CREATE TABLE RESEÑA (
    ID INT IDENTITY PRIMARY KEY,
    UsuarioID INT,
    LugarID INT,
    Comentario NVARCHAR(255),
    Calificación INT,
    Fecha DATETIME,
    FOREIGN KEY (UsuarioID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (LugarID) REFERENCES LUGAR(ID) ON DELETE CASCADE
);
CREATE TABLE EVENTO (
    ID INT IDENTITY PRIMARY KEY,
    Nombre NVARCHAR(150),
    Descripción NVARCHAR(100),
    Fecha DATETIME,
    LugarID INT,
    OrganizadorID INT,
    FOREIGN KEY (LugarID) REFERENCES LUGAR(ID),
    FOREIGN KEY (OrganizadorID) REFERENCES USUARIO(ID)
);
